'''Counting words

COUNT(ACAACTATGCATACTATCGGGAACTATCCT, ACTAT) = 3
COUNT(CGATATATCCATAG, ATA)=3
'''
def COUNT(string, seq):
    '''
    Counting words problem- page 7
    Returns the number of times that a k-mer Pattern appears as a substring of Text, k-mer refers to a string of length k
    Given: {DNA strings} Text and Pattern
    '''
    k=len(seq)
    c=0
    for i in range(len(string)-k+1):
        if string[i:i+k]==seq:
            c+=1
    return c

dna="TCAGTGGAATTCAGTGGACAGTACTTCCCCTGCAGCAGTGGAAAACAGTGGAGCGCCAGTGGACCAGTGGACAGTGGAACCTCCAGTGGAAGATCAGTGGAGACAGTGGAGCAGTGGATCAGTGGAAAACAGTGGACAGTGGAGCAGTGGAAACTCAGTGGACAGTGGACATACAGTGGAACAGTGGACAGTGGACAGTGGACAGTGGATATCAGTGGACGCAGTGGAAAAGATTGCCAGTGGACCAGTGGACAGTGGACCCCCGCCCACAGTGGATGATCAGTGGAGCAGTGGATACATGAGTCAGTGGAAACATTACAGTGGAAGCCAGTGGATACAGTGGATCAGTGGACAGTGGAGCCAGTGGAGCCCGGCAGTGGACACAGTGGAGCAGTGGACTCAGTGGAGTGCAGTGGACAGTGGAGCACCGTAACGAGTCCAGTGGACAGTGGACCAGTGGACAGTGGAGCCAGTGGACAGTGGACAGTGGACCCATCTGATACAGTGGACAGTGGAGTACAGTGGAGTTTGCAGTGGACCGCACAGTGGAAATCCAGTGGAAGCGTCAGTGGAACAGTGGACAGTGGACAGTGGACAGTGGACAGTGGACTCAGTGGACAGTGGACTCAGTGGACAGTGGAGCCCCAGTGGACCAGTGGATCTTGCAGTGGACAGTGGAGTGGAGCCAGTGGACAGTGGATCGGGTGCAGTGGACAACCAGTGGACAGCCAGTGGATCACAGTGGAGGATCCGGACAGTGGAGCAGTGGACAGTGGATCAGTGGAGCTTACTTCACGCAGTGGAGACAGTGGAGAACAGTGGACACGCCCAGTGGACCACAGTGGACAGTGGACAGTGGACAGTGGAGCAGTGGATCAGTGGATGGCCAGTGGATTTCCAGTGGAAGACAGTGGACAGTGGACTACCAGTGGACAGTGGACAGTGGACAGTGGACAGTGGACTCAACCCAGCAGTGGACAGTGGACAGTGGAAGCAGTGGAGGCAGTGGAATAATCCAGTGGACGTGTCAGTGGATCGAGCCAGTGGA"
pattern="CAGTGGACA"
print(COUNT(dna,pattern))