'''Frequent Words Problem

Find the most frequent k-mers in a string
'''
from ba1a import COUNT


def max(arr):
    '''
    Returns the largest number in an array of numbers arr
    '''
    max=arr[0]
    for i in arr:
        if i>max:
            max=i
    return max

def FREQUENTWORDS(str,k):
    '''
    Frequent Words Problem- page 8
    Find the most frequent k-mers in a string
    takes a text and integer k returns all possible most frequent kmers 
    Running time: O(kn^2) where k=length of the k-mer and n=length of the DNA string str
    '''
    counts=[0 for i in range(len(str)-k+1)]
    for i in range(len(counts)):
        pattern=str[i:i+k]
        counts[i]=COUNT(str,pattern)
    max_freq=max(counts)
    seq=[]
    #print(counts)
    for i in range(len(counts)):
        if counts[i]==max_freq:
            s=str[i:k+i]
            if s not in seq:
                seq.append(s)
    return seq

print(FREQUENTWORDS("TGAGCGGGTGAGCGGGAGGTGCGTGGTGAGCGGGCTCTGTAGCAGGTGCGTGGAGGTGCGTGGTGAGCGGGTGAGCGGGAGGTGCGTGGAGGTGCGTGGGCGATCATTTGAGCGGGTGAGCGGGTGAGCGGGAGGTGCGTGGAGGTGCGTGGCTCTGTAGCGCGATCATTCTCTGTAGCTGAGCGGGGCGATCATTTAATGGTTAAGGTGCGTGGTAATGGTTACTCTGTAGCTAATGGTTAGCGATCATTGCGATCATTTGAGCGGGTAATGGTTACTCTGTAGCCTCTGTAGCAGGTGCGTGGGCGATCATTCTCTGTAGCGCGATCATTTAATGGTTAGCGATCATTCTCTGTAGCAGGTGCGTGGTGAGCGGGGCGATCATTTGAGCGGGGCGATCATTAGGTGCGTGGTGAGCGGGTGAGCGGGGCGATCATTGCGATCATTAGGTGCGTGGTAATGGTTATAATGGTTAGCGATCATTCTCTGTAGCTGAGCGGGTGAGCGGGTAATGGTTATGAGCGGGTAATGGTTACTCTGTAGCGCGATCATTTGAGCGGGAGGTGCGTGGTGAGCGGGCTCTGTAGCAGGTGCGTGGCTCTGTAGCAGGTGCGTGGTAATGGTTATAATGGTTAGCGATCATTCTCTGTAGCTAATGGTTATAATGGTTACTCTGTAGCAGGTGCGTGGTAATGGTTATAATGGTTAGCGATCATTTGAGCGGGAGGTGCGTGGCTCTGTAGCTGAGCGGGCTCTGTAGCTGAGCGGGCTCTGTAGCTGAGCGGGTAATGGTTAAGGTGCGTGGTAATGGTTAGCGATCATTTAATGGTTATAATGGTTAAGGTGCGTGGTAATGGTTACTCTGTAGCCTCTGTAGCCTCTGTAGCTGAGCGGGc",12))