'''
Algorithmic Heights
Fibonacci numbers

The Fibonacci numbers 0,1,1,2,3,5,8,13,21,34,… are generated by the following simple rule
Fn=Fn-1 + Fn-2 for n>1
Fn=1 for n=1
Fn=0 for n=0

Given: A positive integer n≤25.
Return: The value of Fn
'''

def fibonacci(num):
    '''takes an int and returns fibonacci this int'''
    a=[0,1];
    for i in range(2,num+1):
        a.append(a[i-1]+a[i-2])
    print(a)
    return a[num]

n=int(input("enter an integer:"))
print("fibonacci of %d is %d" %(n,fibonacci(n)))